// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: drops.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createDrop = `-- name: CreateDrop :one
INSERT INTO drops (name, slug, description, instagram_url)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, description, instagram_url, released_at, created_at
`

type CreateDropParams struct {
	Name         string `json:"name"`
	Slug         string `json:"slug"`
	Description  string `json:"description"`
	InstagramUrl string `json:"instagram_url"`
}

func (q *Queries) CreateDrop(ctx context.Context, arg CreateDropParams) (Drop, error) {
	row := q.db.QueryRowContext(ctx, createDrop,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.InstagramUrl,
	)
	var i Drop
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.InstagramUrl,
		&i.ReleasedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDrop = `-- name: DeleteDrop :exec
DELETE FROM drops WHERE id = $1
`

func (q *Queries) DeleteDrop(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDrop, id)
	return err
}

const getDropByID = `-- name: GetDropByID :one
SELECT id, name, slug, description, instagram_url, released_at, created_at
FROM drops
WHERE id = $1
`

func (q *Queries) GetDropByID(ctx context.Context, id uuid.UUID) (Drop, error) {
	row := q.db.QueryRowContext(ctx, getDropByID, id)
	var i Drop
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.InstagramUrl,
		&i.ReleasedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDropBySlug = `-- name: GetDropBySlug :one
SELECT id, name, slug, description, instagram_url, released_at, created_at
FROM drops
WHERE slug = $1
`

func (q *Queries) GetDropBySlug(ctx context.Context, slug string) (Drop, error) {
	row := q.db.QueryRowContext(ctx, getDropBySlug, slug)
	var i Drop
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.InstagramUrl,
		&i.ReleasedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDrops = `-- name: ListDrops :many
SELECT id, name, slug, description, instagram_url, released_at, created_at
FROM drops
ORDER BY released_at DESC NULLS LAST, created_at DESC
`

func (q *Queries) ListDrops(ctx context.Context) ([]Drop, error) {
	rows, err := q.db.QueryContext(ctx, listDrops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Drop
	for rows.Next() {
		var i Drop
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.InstagramUrl,
			&i.ReleasedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDrop = `-- name: UpdateDrop :one
UPDATE drops SET
    name          = COALESCE($2, name),
    description   = COALESCE($3, description),
    instagram_url = COALESCE($4, instagram_url)
WHERE id = $1
RETURNING id, name, slug, description, instagram_url, released_at, created_at
`

type UpdateDropParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	InstagramUrl string    `json:"instagram_url"`
}

func (q *Queries) UpdateDrop(ctx context.Context, arg UpdateDropParams) (Drop, error) {
	row := q.db.QueryRowContext(ctx, updateDrop,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.InstagramUrl,
	)
	var i Drop
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.InstagramUrl,
		&i.ReleasedAt,
		&i.CreatedAt,
	)
	return i, err
}
